AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  valheim-server-bot

  SAM Template for valheim-server-bot
  Creates a Lambda function with a gateway to acces it, and a DynamoDB table

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30
    MemorySize: 128

Resources:
  ValheimBotApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
    DefinitionBody:
      swagger: "2.0"
      paths:
        /message:
          post:
            produces:
            - application/json
            responses:
              '202':
                description: "Accepted"
                schema:
                  type: object
            x-amazon-apigateway-integration:
              type: AWS
              uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ValheimBotFunction.Arn}/invocations
              httpMethod: POST
              responses:
                default:
                  statusCode: 200
              requestParameters:
                integration.request.header.X-Amz-Invocation-Type: "'Event'"
              passthroughBehavior : when_no_match

  ValheimBotFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.lambda_handler
      Timeout: 100
      Runtime: python3.9
      Architectures:
        - x86_64
      Environment:
        Variables:
          TELEGRAM_TOKEN: SECRET
          SECRET_API_KEY: SECRET
          DEV: 0
          INSTANCE_ID: i-06a490b7dc5c79907
          REGION: eu-central-1
          OWNER_ID: 427448878
      Events:
        MessageReceived:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /message
            Method: post
            RestApiId:
              Ref: ValheimBotApi
      Policies:
        - AmazonEC2FullAccess

Outputs:
  ValheimBotApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ValheimBotApi}.execute-api.${AWS::Region}.amazonaws.com/prod/message/"
  ValheimBotFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt ValheimBotFunction.Arn
  ValheimBotFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt ValheimBotFunction.Arn
