AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  valheim-server-bot

  SAM Template for valheim-server-bot
  Creates a Lambda function with a gateway to acces it, and a DynamoDB table

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30
    MemorySize: 128

Resources:
  ValheimBotFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.lambda_handler
      Timeout: 100
      Runtime: python3.9
      Architectures:
        - x86_64
      Environment:
        Variables:
          TELEGRAM_TOKEN: SECRET
          SECRET_API_KEY: SECRET
          DEV: 0
          INSTANCE_ID: i-06a490b7dc5c79907
          REGION: eu-central-1
          OWNER_ID: 427448878
      Events:
        MessageReceived:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /message
            Method: post
            Auth:
              ApiKeyRequired: true

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  ValheimBotApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  ValheimBotFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt ValheimBotFunction.Arn
  ValheimBotFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt ValheimBotFunction.Arn
